Maj user patron add new fields
rero/invenio-userprofiles pull request #4
Opened 2021-02-11 16:04 UTC by jma

2021-02-24 13:58 UTC, BadrAly requested changes

2021-02-24 13:58 UTC, BadrAly commented on invenio_userprofiles/admin.py
> +        'buisness_phone',
business_phone

2021-02-24 13:58 UTC, BadrAly commented on invenio_userprofiles/config.py
> +USERPROFILES_COUNTRIES = lambda: [('ch', 'Swizerland')]
Switzerland

2021-02-24 13:59 UTC, lauren-d approved these changes

2021-02-25 14:37 UTC, lauren-d approved these changes

2021-02-25 14:51 UTC, BadrAly approved these changes

2021-03-01 06:50 UTC, merged